kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: infiotmgmtproxy-traefik-ingress-controller
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
      - ingressclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses/status
    verbs:
      - update
  - apiGroups:
      - traefik.containo.us
    resources:
      - middlewares
      - ingressroutes
      - traefikservices
      - ingressroutetcps
      - ingressrouteudps
      - tlsoptions
      - tlsstores
    verbs:
      - get
      - list
      - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: infiotmgmtproxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: infiotmgmtproxy-traefik-ingress-controller
subjects:
  - kind: ServiceAccount
    name: traefik-ingress-controller
    namespace: infiotmgmtproxy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: infiotmgmtproxy
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik
  namespace: infiotmgmtproxy
  labels:
    app: traefik
spec:
  replicas: 2
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.3
          ports:
          - name: infiotsvc
            containerPort: 4500
          args:
          - --providers.kubernetescrd
          - --api.dashboard=false
          - --log=true
          - --log.level=INFO
          - --accesslog=true
          - --entrypoints.web.address=:80
          - --entrypoints.websecure.address=:443
          - --entrypoints.infiotsvc.address=:4500
          - --providers.kubernetescrd.allowcrossnamespace=true
          - --providers.kubernetescrd.namespaces=infiotmgmtproxy
---
kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
  namespace: infiotmgmtproxy
spec:
  selector:
    app: traefik
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - protocol: TCP
      port: 4500
      name: infiotsvc
